- hosts: localhost
  gather_facts: yes
  connection: ssh
  vars:
    identifier: unknown
    base_image: "https://sfcbr.shakenfist.com/static/ubuntu2004-ci-template.qcow2"
    base_image_user: "ubuntu"

  tasks:
    - name: Create a primary instance
      sf_instance:
        name: "primary"
        cpu: 12
        ram: 16384
        disks:
          - "100@{{base_image}}"
          - "30@sf://label/ci-images/dependencies"
        networkspecs:
          - network_uuid="{{identifier}}",address=10.0.0.10
        ssh_key: "{{ lookup('file', '/srv/github/id_ci.pub') }}"
        namespace: "{{identifier}}"
        state: present
      register: primary

    - name: Add primary node to ansible
      add_host:
        hostname: primary
        egress_ip: "{{primary['meta']['network_interfaces'][0]['ipv4']}}"
        ansible_ssh_host: "{{primary['meta']['network_interfaces'][0]['ipv4']}}"
        ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -o GlobalKnownHostsFile=/dev/null -o UserKnownHostsFile=/dev/null"
        ansible_ssh_user: "{{base_image_user}}"
        ansible_ssh_private_key_file: "/srv/github/id_ci"
        sf_uuid: "{{primary['meta']['uuid']}}"
        groups: sfall

    - name: Log instance details
      debug:
        msg:
          - "Primary: is {{primary['meta']['uuid']}} at {{primary['meta']['network_interfaces'][0]['ipv4']}}"
