name: Test rocky-9-python-openstackclient

on:
  push:
    branches:
      - develop
      - v*-releases
  pull_request:
    branches:
      - develop
      - v*-releases

jobs:
  rocky-9-python-openstackclient:
    runs-on: self-hosted
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    # NOTE(mikal): git repos are checked out to /srv/github/_work/{repo}/{repo}
    # which is available as GITHUB_WORKSPACE. You can find other environment
    # variables at https://docs.github.com/en/actions/learn-github-actions/environment-variables

    steps:
      - name: Set environment variables
        run: |
          echo "SF_HEAD_SHA=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
          echo "SHAKENFIST_NAMESPACE=$(hostname)" >> $GITHUB_ENV

      - name: Checkout kerbside-patches
        uses: actions/checkout@v4
        with:
          path: kerbside-patches
          fetch-depth: 0

      - name: Build the instance which actually runs tests
        run: |
          cd ${GITHUB_WORKSPACE}/kerbside-patches/.github
          ansible-playbook -i /home/debian/ansible-hosts \
              --extra-vars "identifier=${SHAKENFIST_NAMESPACE} source_path=${GITHUB_WORKSPACE} \
              base_image=sf://label/ci-images/rocky-9 base_image_user=cloud-user" \
              ci-topology.yml

      - name: Copy source code to primary
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          cd ${GITHUB_WORKSPACE}
          scp -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null -rp kerbside-patches \
              cloud-user@$primary:.

      - name: Install missing dependencies
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          cd ${GITHUB_WORKSPACE}

          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null cloud-user@$primary \
              "sudo pip3 install yq"
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null cloud-user@$primary \
              "sudo dnf install -y moreutils"


      - name: Attempt to apply patches to python-openstackclient-2023.1
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          cd ${GITHUB_WORKSPACE}
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null cloud-user@$primary \
              "cd kerbside-patches; ./testapply.sh python-openstackclient-2023.1"


      - name: Attempt to apply patches to python-openstackclient-2023.2
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          cd ${GITHUB_WORKSPACE}
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null cloud-user@$primary \
              "cd kerbside-patches; ./testapply.sh python-openstackclient-2023.2"


      - name: Attempt to apply patches to python-openstackclient-2024.1
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          cd ${GITHUB_WORKSPACE}
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null cloud-user@$primary \
              "cd kerbside-patches; ./testapply.sh python-openstackclient-2024.1"


      - name: Attempt to apply patches to python-openstackclient
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          cd ${GITHUB_WORKSPACE}
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null cloud-user@$primary \
              "cd kerbside-patches; ./testapply.sh python-openstackclient"

